version: "3.9"
services:
  todo_app:
    image: todo_app
    build:
      context: ./todo_app
    ports:
      - "8000:80"
    volumes:
      - todo_data:/app/data
    networks:
      - app_network

  shorturl_app:
    image: shorturl_app
    build:
      context: ./shorturl_app
    ports:
      - "8001:80"
    volumes:
      - shorturl_data:/app/data
    networks:
      - app_network

volumes:
  todo_data:
  shorturl_data:

networks:
  app_network:
